### ISSUE TITLE
mage doesn't install for arm64

### ISSUE THREAD

**Issue by rickardgranberg** [guiyomh/features#34]
When trying to use the mage feature in a `linux/arm64` dev container, installation fails with:

```
/usr/local/bin/mage: Invalid ELF image for this architecture
Feature "mage" (ghcr.io/guiyomh/features/mage) failed to install!
```

I'm assuming it's because it's downloading the `linux/amd64` version regardless of runtime environment:
https://github.com/guiyomh/features/blob/9fa050599670f0e7fff1fe62fc63277b5560c822/src/mage/install.sh#L105

I should mention that I get this problem when using the Devcontainers CLI/CI to build a container on CI/CD (Docker/Linux). I don't see it when I build the container locally (Docker Desktop/WSL) oddly enough.

**Comment by rickardgranberg** [comment]
Please disregard this, problem was qemu was missing on the CI/CD VM

**Comment by guiyomh** [comment]
No worries. Have a nice day and thanks for using my features
