### ISSUE TITLE
golangci-lint feature: arm64 support

### ISSUE THREAD

**Issue by ryepup** [guiyomh/features#35]
The installer script always downloads the amd64 binary, which fails on arm64 machines like newer macs.

https://github.com/guiyomh/features/blob/9fa050599670f0e7fff1fe62fc63277b5560c822/src/golangci-lint/install.sh#L107

golangci-lint does publish arm64 packages, I think a `dpkg --print-architecture` and another `if` statement would do it.

**Comment by guiyomh** [comment]
thx for this good catch ! I'll made a fix.
